// -------------------------------------------------------------
// 
// File Name: check/hdlsrc/gm_untitled1/Subsystem_ip_addr_decoder.v
// Created: 2026-03-08 12:02:41
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip_addr_decoder
// Source Path: Subsystem_ip/Subsystem_ip_axi_lite/Subsystem_ip_addr_decoder
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip_addr_decoder
          (clk,
           reset,
           data_write,
           addr_write,
           wr_enb,
           addr_read,
           rd_enb,
           read_ip_timestamp,
           read_y_0,
           read_y_1,
           data_read,
           write_axi_enable,
           write_In1_0,
           write_In1_1,
           write_theta,
           write_In2_0,
           write_In2_1,
           write_In3_0,
           write_In3_1,
           write_In4_0,
           write_In4_1);


  input   clk;
  input   reset;
  input   [31:0] data_write;  // ufix32
  input   [13:0] addr_write;  // ufix14
  input   wr_enb;  // ufix1
  input   [13:0] addr_read;  // ufix14
  input   rd_enb;  // ufix1
  input   [31:0] read_ip_timestamp;  // ufix32
  input   signed [15:0] read_y_0;  // sfix16_En12
  input   signed [15:0] read_y_1;  // sfix16_En12
  output  [31:0] data_read;  // ufix32
  output  write_axi_enable;  // ufix1
  output  signed [15:0] write_In1_0;  // sfix16_En12
  output  signed [15:0] write_In1_1;  // sfix16_En12
  output  signed [15:0] write_theta;  // sfix16_En12
  output  signed [15:0] write_In2_0;  // sfix16_En12
  output  signed [15:0] write_In2_1;  // sfix16_En12
  output  signed [15:0] write_In3_0;  // sfix16_En12
  output  signed [15:0] write_In3_1;  // sfix16_En12
  output  signed [15:0] write_In4_0;  // sfix16_En12
  output  signed [15:0] write_In4_1;  // sfix16_En12


  wire enb;
  wire [6:0] address_select_level1;  // ufix7
  wire const_1;  // ufix1
  reg [31:0] read_reg_ip_timestamp;  // ufix32
  wire decode_sel_y;  // ufix1
  wire strobe_sel_y;  // ufix1
  wire const_zero;  // ufix1
  wire strobe_in_y;  // ufix1
  wire strobe_sw_y;  // ufix1
  reg  strobe_reg_y;  // ufix1
  wire signed [15:0] read_y [0:1];  // sfix16_En12 [2]
  reg signed [15:0] sync_reg_y [0:1];  // sfix16_En12 [2]
  wire [31:0] data_slice_y_1 [0:1];  // ufix32 [2]
  wire [31:0] data_slice_y_1_0;  // ufix32
  wire [31:0] data_slice_y_1_1;  // ufix32
  wire [31:0] const_0;  // ufix32
  reg [31:0] mux_out0_level1;  // ufix32
  wire decode_sel_axi_enable_1_1;  // ufix1
  wire reg_enb_axi_enable_1_1;  // ufix1
  wire data_in_axi_enable;  // ufix1
  reg  data_reg_axi_enable_1_1;  // ufix1
  wire decode_sel_In1;  // ufix1
  wire strobe_sel_In1;  // ufix1
  wire const_zero_1;  // ufix1
  wire strobe_in_In1;  // ufix1
  wire strobe_sw_In1;  // ufix1
  wire decode_sel_In1_1_1;  // ufix1
  wire reg_enb_In1_1_1;  // ufix1
  wire signed [15:0] data_in_In1;  // sfix16_En12
  reg signed [15:0] data_reg_In1_1_1;  // sfix16_En12
  wire decode_sel_In1_2_1;  // ufix1
  wire reg_enb_In1_2_1;  // ufix1
  reg  strobe_reg_In1;  // ufix1
  reg signed [15:0] data_reg_In1_2_1;  // sfix16_En12
  wire signed [15:0] write_reg_In1 [0:1];  // sfix16_En12 [2]
  reg signed [15:0] sync_reg_In1_1 [0:1];  // sfix16_En12 [2]
  wire decode_sel_theta_1_1;  // ufix1
  wire reg_enb_theta_1_1;  // ufix1
  wire signed [15:0] data_in_theta;  // sfix16_En12
  reg signed [15:0] data_reg_theta_1_1;  // sfix16_En12
  wire decode_sel_In2;  // ufix1
  wire strobe_sel_In2;  // ufix1
  wire const_zero_2;  // ufix1
  wire strobe_in_In2;  // ufix1
  wire strobe_sw_In2;  // ufix1
  wire decode_sel_In2_1_1;  // ufix1
  wire reg_enb_In2_1_1;  // ufix1
  wire signed [15:0] data_in_In2;  // sfix16_En12
  reg signed [15:0] data_reg_In2_1_1;  // sfix16_En12
  wire decode_sel_In2_2_1;  // ufix1
  wire reg_enb_In2_2_1;  // ufix1
  reg  strobe_reg_In2;  // ufix1
  reg signed [15:0] data_reg_In2_2_1;  // sfix16_En12
  wire signed [15:0] write_reg_In2 [0:1];  // sfix16_En12 [2]
  reg signed [15:0] sync_reg_In2_1 [0:1];  // sfix16_En12 [2]
  wire decode_sel_In3;  // ufix1
  wire strobe_sel_In3;  // ufix1
  wire const_zero_3;  // ufix1
  wire strobe_in_In3;  // ufix1
  wire strobe_sw_In3;  // ufix1
  wire decode_sel_In3_1_1;  // ufix1
  wire reg_enb_In3_1_1;  // ufix1
  wire signed [15:0] data_in_In3;  // sfix16_En12
  reg signed [15:0] data_reg_In3_1_1;  // sfix16_En12
  wire decode_sel_In3_2_1;  // ufix1
  wire reg_enb_In3_2_1;  // ufix1
  reg  strobe_reg_In3;  // ufix1
  reg signed [15:0] data_reg_In3_2_1;  // sfix16_En12
  wire signed [15:0] write_reg_In3 [0:1];  // sfix16_En12 [2]
  reg signed [15:0] sync_reg_In3_1 [0:1];  // sfix16_En12 [2]
  wire decode_sel_In4;  // ufix1
  wire strobe_sel_In4;  // ufix1
  wire const_zero_4;  // ufix1
  wire strobe_in_In4;  // ufix1
  wire strobe_sw_In4;  // ufix1
  wire decode_sel_In4_1_1;  // ufix1
  wire reg_enb_In4_1_1;  // ufix1
  wire signed [15:0] data_in_In4;  // sfix16_En12
  reg signed [15:0] data_reg_In4_1_1;  // sfix16_En12
  wire decode_sel_In4_2_1;  // ufix1
  wire reg_enb_In4_2_1;  // ufix1
  reg  strobe_reg_In4;  // ufix1
  reg signed [15:0] data_reg_In4_2_1;  // sfix16_En12
  wire signed [15:0] write_reg_In4 [0:1];  // sfix16_En12 [2]
  reg signed [15:0] sync_reg_In4_1 [0:1];  // sfix16_En12 [2]
  reg signed [31:0] reg_y_t_0_0;  // int32
  reg signed [31:0] reg_y_t_1;  // int32
  reg signed [31:0] sync_reg_In1_t_0_0;  // int32
  reg signed [31:0] sync_reg_In1_t_1;  // int32
  reg signed [31:0] sync_reg_In2_t_0_0;  // int32
  reg signed [31:0] sync_reg_In2_t_1;  // int32
  reg signed [31:0] sync_reg_In3_t_0_0;  // int32
  reg signed [31:0] sync_reg_In3_t_1;  // int32
  reg signed [31:0] sync_reg_In4_t_0_0;  // int32
  reg signed [31:0] sync_reg_In4_t_1;  // int32


  assign address_select_level1 = addr_read[6:0];

  assign const_1 = 1'b1;

  assign enb = const_1;

  always @(posedge clk or posedge reset)
    begin : reg_ip_timestamp_process
      if (reset == 1'b1) begin
        read_reg_ip_timestamp <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          read_reg_ip_timestamp <= read_ip_timestamp;
        end
      end
    end

  assign decode_sel_y = addr_write == 14'b00000001010010;

  assign strobe_sel_y = decode_sel_y & wr_enb;

  assign const_zero = 1'b0;

  assign strobe_in_y = data_write[0];

  assign strobe_sw_y = (strobe_sel_y == 1'b0 ? const_zero :
              strobe_in_y);

  always @(posedge clk or posedge reset)
    begin : reg_rsvd_process
      if (reset == 1'b1) begin
        strobe_reg_y <= 1'b0;
      end
      else begin
        if (enb) begin
          strobe_reg_y <= strobe_sw_y;
        end
      end
    end

  assign read_y[0] = read_y_0;
  assign read_y[1] = read_y_1;

  always @(posedge clk or posedge reset)
    begin : reg_y_process
      if (reset == 1'b1) begin
        for(reg_y_t_1 = 32'sd0; reg_y_t_1 <= 32'sd1; reg_y_t_1 = reg_y_t_1 + 32'sd1) begin
          sync_reg_y[reg_y_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb && strobe_reg_y) begin
          for(reg_y_t_0_0 = 32'sd0; reg_y_t_0_0 <= 32'sd1; reg_y_t_0_0 = reg_y_t_0_0 + 32'sd1) begin
            sync_reg_y[reg_y_t_0_0] <= read_y[reg_y_t_0_0];
          end
        end
      end
    end


  genvar ii1;
  generate
    for(ii1 = 32'sd0; ii1 <= 32'sd1; ii1 = ii1 + 32'sd1) begin:data_slice_y_1_gen
      assign data_slice_y_1[ii1] = {{16{sync_reg_y[ii1][15]}}, sync_reg_y[ii1]};
    end
  endgenerate

  assign data_slice_y_1_0 = data_slice_y_1[0];

  assign data_slice_y_1_1 = data_slice_y_1[1];

  assign const_0 = 32'b00000000000000000000000000000000;

  always @(address_select_level1, const_0, data_slice_y_1_0, data_slice_y_1_1,
       read_reg_ip_timestamp) begin
    case ( address_select_level1)
      7'b0000010 :
        begin
          mux_out0_level1 = read_reg_ip_timestamp;
        end
      7'b1010000 :
        begin
          mux_out0_level1 = data_slice_y_1_0;
        end
      7'b1010001 :
        begin
          mux_out0_level1 = data_slice_y_1_1;
        end
      default :
        begin
          mux_out0_level1 = const_0;
        end
    endcase
  end

  assign data_read = mux_out0_level1;

  assign decode_sel_axi_enable_1_1 = addr_write == 14'b00000000000001;

  assign reg_enb_axi_enable_1_1 = decode_sel_axi_enable_1_1 & wr_enb;

  assign data_in_axi_enable = data_write[0];

  always @(posedge clk or posedge reset)
    begin : reg_axi_enable_1_1_process
      if (reset == 1'b1) begin
        data_reg_axi_enable_1_1 <= 1'b1;
      end
      else begin
        if (enb && reg_enb_axi_enable_1_1) begin
          data_reg_axi_enable_1_1 <= data_in_axi_enable;
        end
      end
    end

  assign write_axi_enable = data_reg_axi_enable_1_1;

  assign decode_sel_In1 = addr_write == 14'b00000001000010;

  assign strobe_sel_In1 = decode_sel_In1 & wr_enb;

  assign const_zero_1 = 1'b0;

  assign strobe_in_In1 = data_write[0];

  assign strobe_sw_In1 = (strobe_sel_In1 == 1'b0 ? const_zero_1 :
              strobe_in_In1);

  assign decode_sel_In1_1_1 = addr_write == 14'b00000001000000;

  assign reg_enb_In1_1_1 = decode_sel_In1_1_1 & wr_enb;

  assign data_in_In1 = $signed(data_write[15:0]);

  always @(posedge clk or posedge reset)
    begin : reg_In1_1_1_process
      if (reset == 1'b1) begin
        data_reg_In1_1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb && reg_enb_In1_1_1) begin
          data_reg_In1_1_1 <= data_in_In1;
        end
      end
    end

  assign decode_sel_In1_2_1 = addr_write == 14'b00000001000001;

  assign reg_enb_In1_2_1 = decode_sel_In1_2_1 & wr_enb;

  always @(posedge clk or posedge reset)
    begin : reg_rsvd_1_process
      if (reset == 1'b1) begin
        strobe_reg_In1 <= 1'b0;
      end
      else begin
        if (enb) begin
          strobe_reg_In1 <= strobe_sw_In1;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : reg_In1_2_1_process
      if (reset == 1'b1) begin
        data_reg_In1_2_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb && reg_enb_In1_2_1) begin
          data_reg_In1_2_1 <= data_in_In1;
        end
      end
    end

  assign write_reg_In1[0] = data_reg_In1_1_1;
  assign write_reg_In1[1] = data_reg_In1_2_1;

  always @(posedge clk or posedge reset)
    begin : sync_reg_In1_process
      if (reset == 1'b1) begin
        for(sync_reg_In1_t_1 = 32'sd0; sync_reg_In1_t_1 <= 32'sd1; sync_reg_In1_t_1 = sync_reg_In1_t_1 + 32'sd1) begin
          sync_reg_In1_1[sync_reg_In1_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb && strobe_reg_In1) begin
          for(sync_reg_In1_t_0_0 = 32'sd0; sync_reg_In1_t_0_0 <= 32'sd1; sync_reg_In1_t_0_0 = sync_reg_In1_t_0_0 + 32'sd1) begin
            sync_reg_In1_1[sync_reg_In1_t_0_0] <= write_reg_In1[sync_reg_In1_t_0_0];
          end
        end
      end
    end

  assign write_In1_0 = sync_reg_In1_1[0];

  assign write_In1_1 = sync_reg_In1_1[1];

  assign decode_sel_theta_1_1 = addr_write == 14'b00000001000011;

  assign reg_enb_theta_1_1 = decode_sel_theta_1_1 & wr_enb;

  assign data_in_theta = $signed(data_write[15:0]);

  always @(posedge clk or posedge reset)
    begin : reg_theta_1_1_process
      if (reset == 1'b1) begin
        data_reg_theta_1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb && reg_enb_theta_1_1) begin
          data_reg_theta_1_1 <= data_in_theta;
        end
      end
    end

  assign write_theta = data_reg_theta_1_1;

  assign decode_sel_In2 = addr_write == 14'b00000001000110;

  assign strobe_sel_In2 = decode_sel_In2 & wr_enb;

  assign const_zero_2 = 1'b0;

  assign strobe_in_In2 = data_write[0];

  assign strobe_sw_In2 = (strobe_sel_In2 == 1'b0 ? const_zero_2 :
              strobe_in_In2);

  assign decode_sel_In2_1_1 = addr_write == 14'b00000001000100;

  assign reg_enb_In2_1_1 = decode_sel_In2_1_1 & wr_enb;

  assign data_in_In2 = $signed(data_write[15:0]);

  always @(posedge clk or posedge reset)
    begin : reg_In2_1_1_process
      if (reset == 1'b1) begin
        data_reg_In2_1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb && reg_enb_In2_1_1) begin
          data_reg_In2_1_1 <= data_in_In2;
        end
      end
    end

  assign decode_sel_In2_2_1 = addr_write == 14'b00000001000101;

  assign reg_enb_In2_2_1 = decode_sel_In2_2_1 & wr_enb;

  always @(posedge clk or posedge reset)
    begin : reg_rsvd_2_process
      if (reset == 1'b1) begin
        strobe_reg_In2 <= 1'b0;
      end
      else begin
        if (enb) begin
          strobe_reg_In2 <= strobe_sw_In2;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : reg_In2_2_1_process
      if (reset == 1'b1) begin
        data_reg_In2_2_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb && reg_enb_In2_2_1) begin
          data_reg_In2_2_1 <= data_in_In2;
        end
      end
    end

  assign write_reg_In2[0] = data_reg_In2_1_1;
  assign write_reg_In2[1] = data_reg_In2_2_1;

  always @(posedge clk or posedge reset)
    begin : sync_reg_In2_process
      if (reset == 1'b1) begin
        for(sync_reg_In2_t_1 = 32'sd0; sync_reg_In2_t_1 <= 32'sd1; sync_reg_In2_t_1 = sync_reg_In2_t_1 + 32'sd1) begin
          sync_reg_In2_1[sync_reg_In2_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb && strobe_reg_In2) begin
          for(sync_reg_In2_t_0_0 = 32'sd0; sync_reg_In2_t_0_0 <= 32'sd1; sync_reg_In2_t_0_0 = sync_reg_In2_t_0_0 + 32'sd1) begin
            sync_reg_In2_1[sync_reg_In2_t_0_0] <= write_reg_In2[sync_reg_In2_t_0_0];
          end
        end
      end
    end

  assign write_In2_0 = sync_reg_In2_1[0];

  assign write_In2_1 = sync_reg_In2_1[1];

  assign decode_sel_In3 = addr_write == 14'b00000001001010;

  assign strobe_sel_In3 = decode_sel_In3 & wr_enb;

  assign const_zero_3 = 1'b0;

  assign strobe_in_In3 = data_write[0];

  assign strobe_sw_In3 = (strobe_sel_In3 == 1'b0 ? const_zero_3 :
              strobe_in_In3);

  assign decode_sel_In3_1_1 = addr_write == 14'b00000001001000;

  assign reg_enb_In3_1_1 = decode_sel_In3_1_1 & wr_enb;

  assign data_in_In3 = $signed(data_write[15:0]);

  always @(posedge clk or posedge reset)
    begin : reg_In3_1_1_process
      if (reset == 1'b1) begin
        data_reg_In3_1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb && reg_enb_In3_1_1) begin
          data_reg_In3_1_1 <= data_in_In3;
        end
      end
    end

  assign decode_sel_In3_2_1 = addr_write == 14'b00000001001001;

  assign reg_enb_In3_2_1 = decode_sel_In3_2_1 & wr_enb;

  always @(posedge clk or posedge reset)
    begin : reg_rsvd_3_process
      if (reset == 1'b1) begin
        strobe_reg_In3 <= 1'b0;
      end
      else begin
        if (enb) begin
          strobe_reg_In3 <= strobe_sw_In3;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : reg_In3_2_1_process
      if (reset == 1'b1) begin
        data_reg_In3_2_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb && reg_enb_In3_2_1) begin
          data_reg_In3_2_1 <= data_in_In3;
        end
      end
    end

  assign write_reg_In3[0] = data_reg_In3_1_1;
  assign write_reg_In3[1] = data_reg_In3_2_1;

  always @(posedge clk or posedge reset)
    begin : sync_reg_In3_process
      if (reset == 1'b1) begin
        for(sync_reg_In3_t_1 = 32'sd0; sync_reg_In3_t_1 <= 32'sd1; sync_reg_In3_t_1 = sync_reg_In3_t_1 + 32'sd1) begin
          sync_reg_In3_1[sync_reg_In3_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb && strobe_reg_In3) begin
          for(sync_reg_In3_t_0_0 = 32'sd0; sync_reg_In3_t_0_0 <= 32'sd1; sync_reg_In3_t_0_0 = sync_reg_In3_t_0_0 + 32'sd1) begin
            sync_reg_In3_1[sync_reg_In3_t_0_0] <= write_reg_In3[sync_reg_In3_t_0_0];
          end
        end
      end
    end

  assign write_In3_0 = sync_reg_In3_1[0];

  assign write_In3_1 = sync_reg_In3_1[1];

  assign decode_sel_In4 = addr_write == 14'b00000001001110;

  assign strobe_sel_In4 = decode_sel_In4 & wr_enb;

  assign const_zero_4 = 1'b0;

  assign strobe_in_In4 = data_write[0];

  assign strobe_sw_In4 = (strobe_sel_In4 == 1'b0 ? const_zero_4 :
              strobe_in_In4);

  assign decode_sel_In4_1_1 = addr_write == 14'b00000001001100;

  assign reg_enb_In4_1_1 = decode_sel_In4_1_1 & wr_enb;

  assign data_in_In4 = $signed(data_write[15:0]);

  always @(posedge clk or posedge reset)
    begin : reg_In4_1_1_process
      if (reset == 1'b1) begin
        data_reg_In4_1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb && reg_enb_In4_1_1) begin
          data_reg_In4_1_1 <= data_in_In4;
        end
      end
    end

  assign decode_sel_In4_2_1 = addr_write == 14'b00000001001101;

  assign reg_enb_In4_2_1 = decode_sel_In4_2_1 & wr_enb;

  always @(posedge clk or posedge reset)
    begin : reg_rsvd_4_process
      if (reset == 1'b1) begin
        strobe_reg_In4 <= 1'b0;
      end
      else begin
        if (enb) begin
          strobe_reg_In4 <= strobe_sw_In4;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : reg_In4_2_1_process
      if (reset == 1'b1) begin
        data_reg_In4_2_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb && reg_enb_In4_2_1) begin
          data_reg_In4_2_1 <= data_in_In4;
        end
      end
    end

  assign write_reg_In4[0] = data_reg_In4_1_1;
  assign write_reg_In4[1] = data_reg_In4_2_1;

  always @(posedge clk or posedge reset)
    begin : sync_reg_In4_process
      if (reset == 1'b1) begin
        for(sync_reg_In4_t_1 = 32'sd0; sync_reg_In4_t_1 <= 32'sd1; sync_reg_In4_t_1 = sync_reg_In4_t_1 + 32'sd1) begin
          sync_reg_In4_1[sync_reg_In4_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb && strobe_reg_In4) begin
          for(sync_reg_In4_t_0_0 = 32'sd0; sync_reg_In4_t_0_0 <= 32'sd1; sync_reg_In4_t_0_0 = sync_reg_In4_t_0_0 + 32'sd1) begin
            sync_reg_In4_1[sync_reg_In4_t_0_0] <= write_reg_In4[sync_reg_In4_t_0_0];
          end
        end
      end
    end

  assign write_In4_0 = sync_reg_In4_1[0];

  assign write_In4_1 = sync_reg_In4_1[1];

endmodule  // Subsystem_ip_addr_decoder

