// -------------------------------------------------------------
// 
// File Name: check/hdlsrc/gm_untitled1/Subsystem_ip_src_Subsystem.v
// Created: 2026-03-08 12:02:34
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1
// Target subsystem base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// y_re                          ce_out        1
// y_im                          ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip_src_Subsystem
// Source Path: gm_untitled1/Subsystem
// Hierarchy Level: 0
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip_src_Subsystem
          (clk,
           reset,
           clk_enable,
           In1_re,
           In1_im,
           In2_re,
           In2_im,
           In3_re,
           In3_im,
           In4_re,
           In4_im,
           theta,
           ce_out,
           y_re,
           y_im);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] In1_re;  // sfix16_En12
  input   signed [15:0] In1_im;  // sfix16_En12
  input   signed [15:0] In2_re;  // sfix16_En12
  input   signed [15:0] In2_im;  // sfix16_En12
  input   signed [15:0] In3_re;  // sfix16_En12
  input   signed [15:0] In3_im;  // sfix16_En12
  input   signed [15:0] In4_re;  // sfix16_En12
  input   signed [15:0] In4_im;  // sfix16_En12
  input   signed [15:0] theta;  // sfix16_En12
  output  ce_out;
  output  signed [15:0] y_re;  // sfix16_En12
  output  signed [15:0] y_im;  // sfix16_En12


  wire enb;
  reg signed [15:0] delayMatch_reg_re [0:23];  // sfix16_En12 [24]
  reg signed [15:0] delayMatch_reg_im [0:23];  // sfix16_En12 [24]
  reg signed [15:0] delayMatch_reg_next_re [0:23];  // sfix16_En12 [24]
  reg signed [15:0] delayMatch_reg_next_im [0:23];  // sfix16_En12 [24]
  reg signed [15:0] delayMatch_out1_re;  // sfix16_En12
  reg signed [15:0] delayMatch_out1_im;  // sfix16_En12
  wire signed [15:0] Trigonometric_Function_out1;  // sfix16_En14
  wire signed [31:0] Gain4_out1;  // sfix32_En27
  wire signed [63:0] Gain_out1;  // sfix64_En1027
  wire signed [63:0] cos_jsin_out1_re;  // sfix64_En62
  wire signed [63:0] cos_jsin_out1_im;  // sfix64_En62
  wire signed [79:0] Product_mul_temp;  // sfix80_En74
  wire signed [15:0] Product_sub_cast;  // sfix16_En12
  wire signed [79:0] Product_mul_temp_1;  // sfix80_En74
  wire signed [15:0] Product_sub_cast_1;  // sfix16_En12
  wire signed [79:0] Product_mul_temp_2;  // sfix80_En74
  wire signed [15:0] Product_add_cast;  // sfix16_En12
  wire signed [79:0] Product_mul_temp_3;  // sfix80_En74
  wire signed [15:0] Product_add_cast_1;  // sfix16_En12
  wire signed [15:0] Product_out1_re;  // sfix16_En12
  wire signed [15:0] Product_out1_im;  // sfix16_En12
  wire signed [31:0] Gain5_out1;  // sfix32_En27
  wire signed [63:0] Gain1_out1;  // sfix64_En57
  wire signed [63:0] cos_jsin1_out1_re;  // sfix64_En62
  wire signed [63:0] cos_jsin1_out1_im;  // sfix64_En62
  reg signed [15:0] delayMatch2_reg_re [0:23];  // sfix16_En12 [24]
  reg signed [15:0] delayMatch2_reg_im [0:23];  // sfix16_En12 [24]
  reg signed [15:0] delayMatch2_reg_next_re [0:23];  // sfix16_En12 [24]
  reg signed [15:0] delayMatch2_reg_next_im [0:23];  // sfix16_En12 [24]
  reg signed [15:0] delayMatch2_out1_re;  // sfix16_En12
  reg signed [15:0] delayMatch2_out1_im;  // sfix16_En12
  wire signed [79:0] Product1_mul_temp;  // sfix80_En74
  wire signed [15:0] Product1_sub_cast;  // sfix16_En12
  wire signed [79:0] Product1_mul_temp_1;  // sfix80_En74
  wire signed [15:0] Product1_sub_cast_1;  // sfix16_En12
  wire signed [79:0] Product1_mul_temp_2;  // sfix80_En74
  wire signed [15:0] Product1_add_cast;  // sfix16_En12
  wire signed [79:0] Product1_mul_temp_3;  // sfix80_En74
  wire signed [15:0] Product1_add_cast_1;  // sfix16_En12
  wire signed [15:0] Product1_out1_re;  // sfix16_En12
  wire signed [15:0] Product1_out1_im;  // sfix16_En12
  wire signed [15:0] Add_out1_re;  // sfix16_En12
  wire signed [15:0] Add_out1_im;  // sfix16_En12
  wire signed [31:0] Gain6_out1;  // sfix32_En27
  wire signed [63:0] Gain2_out1;  // sfix64_En56
  wire signed [63:0] cos_jsin2_out1_re;  // sfix64_En62
  wire signed [63:0] cos_jsin2_out1_im;  // sfix64_En62
  reg signed [15:0] delayMatch1_reg_re [0:23];  // sfix16_En12 [24]
  reg signed [15:0] delayMatch1_reg_im [0:23];  // sfix16_En12 [24]
  reg signed [15:0] delayMatch1_reg_next_re [0:23];  // sfix16_En12 [24]
  reg signed [15:0] delayMatch1_reg_next_im [0:23];  // sfix16_En12 [24]
  reg signed [15:0] delayMatch1_out1_re;  // sfix16_En12
  reg signed [15:0] delayMatch1_out1_im;  // sfix16_En12
  wire signed [79:0] Product2_mul_temp;  // sfix80_En74
  wire signed [15:0] Product2_sub_cast;  // sfix16_En12
  wire signed [79:0] Product2_mul_temp_1;  // sfix80_En74
  wire signed [15:0] Product2_sub_cast_1;  // sfix16_En12
  wire signed [79:0] Product2_mul_temp_2;  // sfix80_En74
  wire signed [15:0] Product2_add_cast;  // sfix16_En12
  wire signed [79:0] Product2_mul_temp_3;  // sfix80_En74
  wire signed [15:0] Product2_add_cast_1;  // sfix16_En12
  wire signed [15:0] Product2_out1_re;  // sfix16_En12
  wire signed [15:0] Product2_out1_im;  // sfix16_En12
  wire signed [31:0] Gain7_out1;  // sfix32_En27
  wire signed [63:0] Gain3_out1;  // sfix64_En56
  wire signed [63:0] cos_jsin3_out1_re;  // sfix64_En62
  wire signed [63:0] cos_jsin3_out1_im;  // sfix64_En62
  reg signed [15:0] delayMatch3_reg_re [0:23];  // sfix16_En12 [24]
  reg signed [15:0] delayMatch3_reg_im [0:23];  // sfix16_En12 [24]
  reg signed [15:0] delayMatch3_reg_next_re [0:23];  // sfix16_En12 [24]
  reg signed [15:0] delayMatch3_reg_next_im [0:23];  // sfix16_En12 [24]
  reg signed [15:0] delayMatch3_out1_re;  // sfix16_En12
  reg signed [15:0] delayMatch3_out1_im;  // sfix16_En12
  wire signed [79:0] Product3_mul_temp;  // sfix80_En74
  wire signed [15:0] Product3_sub_cast;  // sfix16_En12
  wire signed [79:0] Product3_mul_temp_1;  // sfix80_En74
  wire signed [15:0] Product3_sub_cast_1;  // sfix16_En12
  wire signed [79:0] Product3_mul_temp_2;  // sfix80_En74
  wire signed [15:0] Product3_add_cast;  // sfix16_En12
  wire signed [79:0] Product3_mul_temp_3;  // sfix80_En74
  wire signed [15:0] Product3_add_cast_1;  // sfix16_En12
  wire signed [15:0] Product3_out1_re;  // sfix16_En12
  wire signed [15:0] Product3_out1_im;  // sfix16_En12
  wire signed [15:0] Add1_out1_re;  // sfix16_En12
  wire signed [15:0] Add1_out1_im;  // sfix16_En12
  wire signed [15:0] Add2_out1_re;  // sfix16_En12
  wire signed [15:0] Add2_out1_im;  // sfix16_En12
  reg signed [31:0] delayMatch_t_0_0;  // int32
  reg signed [31:0] delayMatch_t_0_1;  // int32
  reg signed [31:0] delayMatch_t_1;  // int32
  reg signed [31:0] delayMatch2_t_0_0;  // int32
  reg signed [31:0] delayMatch2_t_0_1;  // int32
  reg signed [31:0] delayMatch2_t_1;  // int32
  reg signed [31:0] delayMatch1_t_0_0;  // int32
  reg signed [31:0] delayMatch1_t_0_1;  // int32
  reg signed [31:0] delayMatch1_t_1;  // int32
  reg signed [31:0] delayMatch3_t_0_0;  // int32
  reg signed [31:0] delayMatch3_t_0_1;  // int32
  reg signed [31:0] delayMatch3_t_1;  // int32


  assign enb = clk_enable;

  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        for(delayMatch_t_1 = 32'sd0; delayMatch_t_1 <= 32'sd23; delayMatch_t_1 = delayMatch_t_1 + 32'sd1) begin
          delayMatch_reg_re[delayMatch_t_1] <= 16'sb0000000000000000;
          delayMatch_reg_im[delayMatch_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch_t_0_1 = 32'sd0; delayMatch_t_0_1 <= 32'sd23; delayMatch_t_0_1 = delayMatch_t_0_1 + 32'sd1) begin
            delayMatch_reg_re[delayMatch_t_0_1] <= delayMatch_reg_next_re[delayMatch_t_0_1];
            delayMatch_reg_im[delayMatch_t_0_1] <= delayMatch_reg_next_im[delayMatch_t_0_1];
          end
        end
      end
    end

  always @* begin
    delayMatch_out1_re = delayMatch_reg_re[23];
    delayMatch_out1_im = delayMatch_reg_im[23];
    delayMatch_reg_next_re[0] = In1_re;
    delayMatch_reg_next_im[0] = In1_im;

    for(delayMatch_t_0_0 = 32'sd0; delayMatch_t_0_0 <= 32'sd22; delayMatch_t_0_0 = delayMatch_t_0_0 + 32'sd1) begin
      delayMatch_reg_next_re[delayMatch_t_0_0 + 32'sd1] = delayMatch_reg_re[delayMatch_t_0_0];
      delayMatch_reg_next_im[delayMatch_t_0_0 + 32'sd1] = delayMatch_reg_im[delayMatch_t_0_0];
    end

  end

  Subsystem_ip_src_Trigonometric_Function_block u_Trigonometric_Function (.clk(clk),
                                                                          .reset(reset),
                                                                          .enb(clk_enable),
                                                                          .In1(theta),  // sfix16_En12
                                                                          .Out1(Trigonometric_Function_out1)  // sfix16_En14
                                                                          );

  assign Gain4_out1 = 16'sb0110010010001000 * Trigonometric_Function_out1;

  assign Gain_out1 = 64'sh0000000000000000;

  Subsystem_ip_src_cos_jsin_block u_cos_jsin (.clk(clk),
                                              .reset(reset),
                                              .enb(clk_enable),
                                              .In1(Gain_out1),  // sfix64_En1027
                                              .Out1_re(cos_jsin_out1_re),  // sfix64_En62
                                              .Out1_im(cos_jsin_out1_im)  // sfix64_En62
                                              );

  assign Product_mul_temp = delayMatch_out1_re * cos_jsin_out1_re;
  assign Product_sub_cast = Product_mul_temp[77:62];
  assign Product_mul_temp_1 = delayMatch_out1_im * cos_jsin_out1_im;
  assign Product_sub_cast_1 = Product_mul_temp_1[77:62];
  assign Product_out1_re = Product_sub_cast - Product_sub_cast_1;
  assign Product_mul_temp_2 = delayMatch_out1_im * cos_jsin_out1_re;
  assign Product_add_cast = Product_mul_temp_2[77:62];
  assign Product_mul_temp_3 = delayMatch_out1_re * cos_jsin_out1_im;
  assign Product_add_cast_1 = Product_mul_temp_3[77:62];
  assign Product_out1_im = Product_add_cast + Product_add_cast_1;

  assign Gain5_out1 = 16'sb0110010010001000 * Trigonometric_Function_out1;

  assign Gain1_out1 = {{2{Gain5_out1[31]}}, {Gain5_out1, 30'b000000000000000000000000000000}};

  Subsystem_ip_src_cos_jsin1_block u_cos_jsin1 (.clk(clk),
                                                .reset(reset),
                                                .enb(clk_enable),
                                                .In1(Gain1_out1),  // sfix64_En57
                                                .Out1_re(cos_jsin1_out1_re),  // sfix64_En62
                                                .Out1_im(cos_jsin1_out1_im)  // sfix64_En62
                                                );

  always @(posedge clk or posedge reset)
    begin : delayMatch2_process
      if (reset == 1'b1) begin
        for(delayMatch2_t_1 = 32'sd0; delayMatch2_t_1 <= 32'sd23; delayMatch2_t_1 = delayMatch2_t_1 + 32'sd1) begin
          delayMatch2_reg_re[delayMatch2_t_1] <= 16'sb0000000000000000;
          delayMatch2_reg_im[delayMatch2_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch2_t_0_1 = 32'sd0; delayMatch2_t_0_1 <= 32'sd23; delayMatch2_t_0_1 = delayMatch2_t_0_1 + 32'sd1) begin
            delayMatch2_reg_re[delayMatch2_t_0_1] <= delayMatch2_reg_next_re[delayMatch2_t_0_1];
            delayMatch2_reg_im[delayMatch2_t_0_1] <= delayMatch2_reg_next_im[delayMatch2_t_0_1];
          end
        end
      end
    end

  always @* begin
    delayMatch2_out1_re = delayMatch2_reg_re[23];
    delayMatch2_out1_im = delayMatch2_reg_im[23];
    delayMatch2_reg_next_re[0] = In2_re;
    delayMatch2_reg_next_im[0] = In2_im;

    for(delayMatch2_t_0_0 = 32'sd0; delayMatch2_t_0_0 <= 32'sd22; delayMatch2_t_0_0 = delayMatch2_t_0_0 + 32'sd1) begin
      delayMatch2_reg_next_re[delayMatch2_t_0_0 + 32'sd1] = delayMatch2_reg_re[delayMatch2_t_0_0];
      delayMatch2_reg_next_im[delayMatch2_t_0_0 + 32'sd1] = delayMatch2_reg_im[delayMatch2_t_0_0];
    end

  end

  assign Product1_mul_temp = cos_jsin1_out1_re * delayMatch2_out1_re;
  assign Product1_sub_cast = Product1_mul_temp[77:62];
  assign Product1_mul_temp_1 = cos_jsin1_out1_im * delayMatch2_out1_im;
  assign Product1_sub_cast_1 = Product1_mul_temp_1[77:62];
  assign Product1_out1_re = Product1_sub_cast - Product1_sub_cast_1;
  assign Product1_mul_temp_2 = cos_jsin1_out1_im * delayMatch2_out1_re;
  assign Product1_add_cast = Product1_mul_temp_2[77:62];
  assign Product1_mul_temp_3 = cos_jsin1_out1_re * delayMatch2_out1_im;
  assign Product1_add_cast_1 = Product1_mul_temp_3[77:62];
  assign Product1_out1_im = Product1_add_cast + Product1_add_cast_1;

  assign Add_out1_re = Product_out1_re + Product1_out1_re;
  assign Add_out1_im = Product_out1_im + Product1_out1_im;

  assign Gain6_out1 = 16'sb0110010010001000 * Trigonometric_Function_out1;

  assign Gain2_out1 = {{2{Gain6_out1[31]}}, {Gain6_out1, 30'b000000000000000000000000000000}};

  Subsystem_ip_src_cos_jsin2_block u_cos_jsin2 (.clk(clk),
                                                .reset(reset),
                                                .enb(clk_enable),
                                                .In1(Gain2_out1),  // sfix64_En56
                                                .Out1_re(cos_jsin2_out1_re),  // sfix64_En62
                                                .Out1_im(cos_jsin2_out1_im)  // sfix64_En62
                                                );

  always @(posedge clk or posedge reset)
    begin : delayMatch1_process
      if (reset == 1'b1) begin
        for(delayMatch1_t_1 = 32'sd0; delayMatch1_t_1 <= 32'sd23; delayMatch1_t_1 = delayMatch1_t_1 + 32'sd1) begin
          delayMatch1_reg_re[delayMatch1_t_1] <= 16'sb0000000000000000;
          delayMatch1_reg_im[delayMatch1_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch1_t_0_1 = 32'sd0; delayMatch1_t_0_1 <= 32'sd23; delayMatch1_t_0_1 = delayMatch1_t_0_1 + 32'sd1) begin
            delayMatch1_reg_re[delayMatch1_t_0_1] <= delayMatch1_reg_next_re[delayMatch1_t_0_1];
            delayMatch1_reg_im[delayMatch1_t_0_1] <= delayMatch1_reg_next_im[delayMatch1_t_0_1];
          end
        end
      end
    end

  always @* begin
    delayMatch1_out1_re = delayMatch1_reg_re[23];
    delayMatch1_out1_im = delayMatch1_reg_im[23];
    delayMatch1_reg_next_re[0] = In3_re;
    delayMatch1_reg_next_im[0] = In3_im;

    for(delayMatch1_t_0_0 = 32'sd0; delayMatch1_t_0_0 <= 32'sd22; delayMatch1_t_0_0 = delayMatch1_t_0_0 + 32'sd1) begin
      delayMatch1_reg_next_re[delayMatch1_t_0_0 + 32'sd1] = delayMatch1_reg_re[delayMatch1_t_0_0];
      delayMatch1_reg_next_im[delayMatch1_t_0_0 + 32'sd1] = delayMatch1_reg_im[delayMatch1_t_0_0];
    end

  end

  assign Product2_mul_temp = cos_jsin2_out1_re * delayMatch1_out1_re;
  assign Product2_sub_cast = Product2_mul_temp[77:62];
  assign Product2_mul_temp_1 = cos_jsin2_out1_im * delayMatch1_out1_im;
  assign Product2_sub_cast_1 = Product2_mul_temp_1[77:62];
  assign Product2_out1_re = Product2_sub_cast - Product2_sub_cast_1;
  assign Product2_mul_temp_2 = cos_jsin2_out1_im * delayMatch1_out1_re;
  assign Product2_add_cast = Product2_mul_temp_2[77:62];
  assign Product2_mul_temp_3 = cos_jsin2_out1_re * delayMatch1_out1_im;
  assign Product2_add_cast_1 = Product2_mul_temp_3[77:62];
  assign Product2_out1_im = Product2_add_cast + Product2_add_cast_1;

  assign Gain7_out1 = 16'sb0110010010001000 * Trigonometric_Function_out1;

  assign Gain3_out1 = 32'sb01100000000000000000000000000000 * Gain7_out1;

  Subsystem_ip_src_cos_jsin3_block u_cos_jsin3 (.clk(clk),
                                                .reset(reset),
                                                .enb(clk_enable),
                                                .In1(Gain3_out1),  // sfix64_En56
                                                .Out1_re(cos_jsin3_out1_re),  // sfix64_En62
                                                .Out1_im(cos_jsin3_out1_im)  // sfix64_En62
                                                );

  always @(posedge clk or posedge reset)
    begin : delayMatch3_process
      if (reset == 1'b1) begin
        for(delayMatch3_t_1 = 32'sd0; delayMatch3_t_1 <= 32'sd23; delayMatch3_t_1 = delayMatch3_t_1 + 32'sd1) begin
          delayMatch3_reg_re[delayMatch3_t_1] <= 16'sb0000000000000000;
          delayMatch3_reg_im[delayMatch3_t_1] <= 16'sb0000000000000000;
        end
      end
      else begin
        if (enb) begin
          for(delayMatch3_t_0_1 = 32'sd0; delayMatch3_t_0_1 <= 32'sd23; delayMatch3_t_0_1 = delayMatch3_t_0_1 + 32'sd1) begin
            delayMatch3_reg_re[delayMatch3_t_0_1] <= delayMatch3_reg_next_re[delayMatch3_t_0_1];
            delayMatch3_reg_im[delayMatch3_t_0_1] <= delayMatch3_reg_next_im[delayMatch3_t_0_1];
          end
        end
      end
    end

  always @* begin
    delayMatch3_out1_re = delayMatch3_reg_re[23];
    delayMatch3_out1_im = delayMatch3_reg_im[23];
    delayMatch3_reg_next_re[0] = In4_re;
    delayMatch3_reg_next_im[0] = In4_im;

    for(delayMatch3_t_0_0 = 32'sd0; delayMatch3_t_0_0 <= 32'sd22; delayMatch3_t_0_0 = delayMatch3_t_0_0 + 32'sd1) begin
      delayMatch3_reg_next_re[delayMatch3_t_0_0 + 32'sd1] = delayMatch3_reg_re[delayMatch3_t_0_0];
      delayMatch3_reg_next_im[delayMatch3_t_0_0 + 32'sd1] = delayMatch3_reg_im[delayMatch3_t_0_0];
    end

  end

  assign Product3_mul_temp = cos_jsin3_out1_re * delayMatch3_out1_re;
  assign Product3_sub_cast = Product3_mul_temp[77:62];
  assign Product3_mul_temp_1 = cos_jsin3_out1_im * delayMatch3_out1_im;
  assign Product3_sub_cast_1 = Product3_mul_temp_1[77:62];
  assign Product3_out1_re = Product3_sub_cast - Product3_sub_cast_1;
  assign Product3_mul_temp_2 = cos_jsin3_out1_im * delayMatch3_out1_re;
  assign Product3_add_cast = Product3_mul_temp_2[77:62];
  assign Product3_mul_temp_3 = cos_jsin3_out1_re * delayMatch3_out1_im;
  assign Product3_add_cast_1 = Product3_mul_temp_3[77:62];
  assign Product3_out1_im = Product3_add_cast + Product3_add_cast_1;

  assign Add1_out1_re = Product2_out1_re + Product3_out1_re;
  assign Add1_out1_im = Product2_out1_im + Product3_out1_im;

  assign Add2_out1_re = Add_out1_re + Add1_out1_re;
  assign Add2_out1_im = Add_out1_im + Add1_out1_im;

  assign y_re = Add2_out1_re;

  assign y_im = Add2_out1_im;

  assign ce_out = clk_enable;

endmodule  // Subsystem_ip_src_Subsystem

