// -------------------------------------------------------------
// 
// File Name: check/hdlsrc/gm_untitled1/Subsystem_ip_src_cos_jsin2_block.v
// Created: 2026-03-08 12:02:34
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip_src_cos_jsin2_block
// Source Path: gm_untitled1/Subsystem/cos + jsin2
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip_src_cos_jsin2_block
          (clk,
           reset,
           enb,
           In1,
           Out1_re,
           Out1_im);


  input   clk;
  input   reset;
  input   enb;
  input   signed [63:0] In1;  // sfix64_En56
  output  signed [63:0] Out1_re;  // sfix64_En62
  output  signed [63:0] Out1_im;  // sfix64_En62


  wire signed [63:0] cos_jsin2_pd1_out1_re;  // sfix64_En62
  wire signed [63:0] cos_jsin2_pd1_out1_im;  // sfix64_En62


  Subsystem_ip_src_cos_jsin2 u_cos_jsin2 (.clk(clk),
                                          .reset(reset),
                                          .enb(enb),
                                          .angle(In1),  // sfix64_En56
                                          .sincos_re(cos_jsin2_pd1_out1_re),  // sfix64_En62
                                          .sincos_im(cos_jsin2_pd1_out1_im)  // sfix64_En62
                                          );

  assign Out1_re = cos_jsin2_pd1_out1_re;

  assign Out1_im = cos_jsin2_pd1_out1_im;

endmodule  // Subsystem_ip_src_cos_jsin2_block

