// -------------------------------------------------------------
// 
// File Name: check/hdlsrc/gm_untitled1/Subsystem_ip_src_Trigonometric_Function.v
// Created: 2026-03-08 12:02:34
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip_src_Trigonometric_Function
// Source Path: gm_untitled1/Subsystem/Trigonometric Function/Trigonometric Function
// Hierarchy Level: 2
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip_src_Trigonometric_Function
          (clk,
           reset,
           enb,
           angle,
           sin);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] angle;  // sfix16_En12
  output  signed [15:0] sin;  // sfix16_En14


  wire init_guard_true_1;
  reg  [11:0] matching_delays_reg;  // ufix1 [12]
  wire init_guard_true_2;
  wire signed [15:0] sininit_guard_default;  // sfix16_En14
  wire signed [15:0] piOver2_1;  // sfix16_En12
  wire Cmp_theta_PiOver2_1;  // ufix1
  wire switch_compare_1;
  wire signed [16:0] negatepiOver2_cast;  // sfix17_En12
  wire signed [16:0] negatepiOver2_cast_1;  // sfix17_En12
  wire signed [15:0] negatepiOver2_1;  // sfix16_En12
  wire Cmp_theta_negatepiOver2_1;  // ufix1
  wire switch_compare_1_1;
  wire Constant_1;  // ufix1
  wire signed [15:0] onePi_1;  // sfix16_En12
  wire signed [15:0] thetaPlusOnePi_1;  // sfix16_En12
  wire Cmp_thetaPlusOnepi_neg_PiOver2_1;  // ufix1
  wire switch_compare_1_2;
  wire Switch3_c1_1;  // ufix1
  wire Switch4_c1_1;  // ufix1
  wire signed [15:0] thetaMinusOnePi_1;  // sfix16_En12
  wire Cmp_thetaMinusOnePi_PiOver2_1;  // ufix1
  wire switch_compare_1_3;
  wire Switch_c1_1;  // ufix1
  wire negate;  // ufix1
  reg  [11:0] negate_reg_reg;  // ufix1 [12]
  wire negate_p;  // ufix1
  wire switch_compare_1_4;
  wire switch_compare_1_5;
  wire signed [15:0] twoPi_1;  // sfix16_En12
  wire switch_compare_1_6;
  wire signed [15:0] thetaPlusTwoPi_1;  // sfix16_En12
  wire signed [15:0] thetaPlusTwoPi_dtc_1;  // sfix16_En14
  wire switch_compare_1_7;
  wire signed [15:0] thetaMinusTwoPi_1;  // sfix16_En12
  wire signed [15:0] thetaMinusTwoPi_dtc_1;  // sfix16_En14
  wire switch_compare_1_8;
  wire signed [15:0] moveFractionLengthUp_dtc;  // sfix16_En14
  wire signed [15:0] thetaPlusOnePi_dtc_1;  // sfix16_En14
  wire signed [15:0] Switch3_1;  // sfix16_En14
  wire signed [15:0] Switch4_1;  // sfix16_En14
  wire signed [15:0] thetaMinusOnePi_dtc_1;  // sfix16_En14
  wire signed [15:0] Switch_1;  // sfix16_En14
  wire signed [15:0] corrected_theta;  // sfix16_En14
  reg signed [15:0] z0_p;  // sfix16_En14
  wire comp_zero1;  // ufix1
  wire switch_compare_1_9;
  wire signed [15:0] lut_value_s1;  // sfix16_En14
  wire signed [15:0] lut_value_temp_0_1_1;  // sfix16_En14
  wire signed [15:0] lut_value_temp_1_1_1;  // sfix16_En14
  wire signed [15:0] z1;  // sfix16_En14
  reg signed [15:0] z1_p;  // sfix16_En14
  wire comp_zero2;  // ufix1
  wire switch_compare_1_10;
  wire signed [15:0] lut_value_s2;  // sfix16_En14
  wire signed [15:0] lut_value_temp_0_2_1;  // sfix16_En14
  wire signed [15:0] lut_value_temp_1_2_1;  // sfix16_En14
  wire signed [15:0] z2;  // sfix16_En14
  reg signed [15:0] z2_p;  // sfix16_En14
  wire comp_zero3;  // ufix1
  wire switch_compare_1_11;
  wire signed [15:0] lut_value_s3;  // sfix16_En14
  wire signed [15:0] lut_value_temp_0_3_1;  // sfix16_En14
  wire signed [15:0] lut_value_temp_1_3_1;  // sfix16_En14
  wire signed [15:0] z3;  // sfix16_En14
  reg signed [15:0] z3_p;  // sfix16_En14
  wire comp_zero4;  // ufix1
  wire switch_compare_1_12;
  wire signed [15:0] lut_value_s4;  // sfix16_En14
  wire signed [15:0] lut_value_temp_0_4_1;  // sfix16_En14
  wire signed [15:0] lut_value_temp_1_4_1;  // sfix16_En14
  wire signed [15:0] z4;  // sfix16_En14
  reg signed [15:0] z4_p;  // sfix16_En14
  wire comp_zero5;  // ufix1
  wire switch_compare_1_13;
  wire signed [15:0] lut_value_s5;  // sfix16_En14
  wire signed [15:0] lut_value_temp_0_5_1;  // sfix16_En14
  wire signed [15:0] lut_value_temp_1_5_1;  // sfix16_En14
  wire signed [15:0] z5;  // sfix16_En14
  reg signed [15:0] z5_p;  // sfix16_En14
  wire comp_zero6;  // ufix1
  wire switch_compare_1_14;
  wire signed [15:0] lut_value_s6;  // sfix16_En14
  wire signed [15:0] lut_value_temp_0_6_1;  // sfix16_En14
  wire signed [15:0] lut_value_temp_1_6_1;  // sfix16_En14
  wire signed [15:0] z6;  // sfix16_En14
  reg signed [15:0] z6_p;  // sfix16_En14
  wire comp_zero7;  // ufix1
  wire switch_compare_1_15;
  wire signed [15:0] lut_value_s7;  // sfix16_En14
  wire signed [15:0] lut_value_temp_0_7_1;  // sfix16_En14
  wire signed [15:0] lut_value_temp_1_7_1;  // sfix16_En14
  wire signed [15:0] z7;  // sfix16_En14
  reg signed [15:0] z7_p;  // sfix16_En14
  wire comp_zero8;  // ufix1
  wire switch_compare_1_16;
  wire signed [15:0] lut_value_s8;  // sfix16_En14
  wire signed [15:0] lut_value_temp_0_8_1;  // sfix16_En14
  wire signed [15:0] lut_value_temp_1_8_1;  // sfix16_En14
  wire signed [15:0] z8;  // sfix16_En14
  reg signed [15:0] z8_p;  // sfix16_En14
  wire comp_zero9;  // ufix1
  wire switch_compare_1_17;
  wire signed [15:0] lut_value_s9;  // sfix16_En14
  wire signed [15:0] lut_value_temp_0_9_1;  // sfix16_En14
  wire signed [15:0] lut_value_temp_1_9_1;  // sfix16_En14
  wire signed [15:0] z9;  // sfix16_En14
  reg signed [15:0] z9_p;  // sfix16_En14
  wire comp_zero10;  // ufix1
  wire switch_compare_1_18;
  wire signed [15:0] lut_value_s10;  // sfix16_En14
  wire signed [15:0] lut_value_temp_0_10_1;  // sfix16_En14
  wire signed [15:0] lut_value_temp_1_10_1;  // sfix16_En14
  wire signed [15:0] z10;  // sfix16_En14
  reg signed [15:0] z10_p;  // sfix16_En14
  wire comp_zero11;  // ufix1
  wire switch_compare_1_19;
  wire switch_compare_1_20;
  wire switch_compare_1_21;
  wire switch_compare_1_22;
  wire switch_compare_1_23;
  wire switch_compare_1_24;
  wire switch_compare_1_25;
  wire switch_compare_1_26;
  wire switch_compare_1_27;
  wire switch_compare_1_28;
  wire switch_compare_1_29;
  wire signed [15:0] y0;  // sfix16_En14
  wire signed [15:0] x0;  // sfix16_En14
  wire signed [15:0] y_temp_0_1_1;  // sfix16_En14
  reg signed [15:0] y_temp_0_p;  // sfix16_En14
  wire signed [15:0] y_temp_1_1_1;  // sfix16_En14
  reg signed [15:0] y_temp_1_p;  // sfix16_En14
  wire signed [15:0] y1;  // sfix16_En14
  reg signed [15:0] y1_p;  // sfix16_En14
  wire switch_compare_1_30;
  wire signed [15:0] x_temp_0_1_1;  // sfix16_En14
  reg signed [15:0] x_temp_0_p;  // sfix16_En14
  wire signed [15:0] x_temp_1_1_1;  // sfix16_En14
  reg signed [15:0] x_temp_1_p;  // sfix16_En14
  wire signed [15:0] x1;  // sfix16_En14
  reg signed [15:0] x1_p;  // sfix16_En14
  wire signed [15:0] x_shift2;  // sfix16_En14
  wire signed [15:0] y_temp_0_2_1;  // sfix16_En14
  wire signed [15:0] y_temp_1_2_1;  // sfix16_En14
  wire signed [15:0] y2;  // sfix16_En14
  reg signed [15:0] y2_p;  // sfix16_En14
  wire switch_compare_1_31;
  wire signed [15:0] y_shift2;  // sfix16_En14
  wire signed [15:0] x_temp_0_2_1;  // sfix16_En14
  wire signed [15:0] x_temp_1_2_1;  // sfix16_En14
  wire signed [15:0] x2;  // sfix16_En14
  reg signed [15:0] x2_p;  // sfix16_En14
  wire signed [15:0] x_shift3;  // sfix16_En14
  wire signed [15:0] y_temp_0_3_1;  // sfix16_En14
  wire signed [15:0] y_temp_1_3_1;  // sfix16_En14
  wire signed [15:0] y3;  // sfix16_En14
  reg signed [15:0] y3_p;  // sfix16_En14
  wire switch_compare_1_32;
  wire signed [15:0] y_shift3;  // sfix16_En14
  wire signed [15:0] x_temp_0_3_1;  // sfix16_En14
  wire signed [15:0] x_temp_1_3_1;  // sfix16_En14
  wire signed [15:0] x3;  // sfix16_En14
  reg signed [15:0] x3_p;  // sfix16_En14
  wire signed [15:0] x_shift4;  // sfix16_En14
  wire signed [15:0] y_temp_0_4_1;  // sfix16_En14
  wire signed [15:0] y_temp_1_4_1;  // sfix16_En14
  wire signed [15:0] y4;  // sfix16_En14
  reg signed [15:0] y4_p;  // sfix16_En14
  wire switch_compare_1_33;
  wire signed [15:0] y_shift4;  // sfix16_En14
  wire signed [15:0] x_temp_0_4_1;  // sfix16_En14
  wire signed [15:0] x_temp_1_4_1;  // sfix16_En14
  wire signed [15:0] x4;  // sfix16_En14
  reg signed [15:0] x4_p;  // sfix16_En14
  wire signed [15:0] x_shift5;  // sfix16_En14
  wire signed [15:0] y_temp_0_5_1;  // sfix16_En14
  wire signed [15:0] y_temp_1_5_1;  // sfix16_En14
  wire signed [15:0] y5;  // sfix16_En14
  reg signed [15:0] y5_p;  // sfix16_En14
  wire switch_compare_1_34;
  wire signed [15:0] y_shift5;  // sfix16_En14
  wire signed [15:0] x_temp_0_5_1;  // sfix16_En14
  wire signed [15:0] x_temp_1_5_1;  // sfix16_En14
  wire signed [15:0] x5;  // sfix16_En14
  reg signed [15:0] x5_p;  // sfix16_En14
  wire signed [15:0] x_shift6;  // sfix16_En14
  wire signed [15:0] y_temp_0_6_1;  // sfix16_En14
  wire signed [15:0] y_temp_1_6_1;  // sfix16_En14
  wire signed [15:0] y6;  // sfix16_En14
  reg signed [15:0] y6_p;  // sfix16_En14
  wire switch_compare_1_35;
  wire signed [15:0] y_shift6;  // sfix16_En14
  wire signed [15:0] x_temp_0_6_1;  // sfix16_En14
  wire signed [15:0] x_temp_1_6_1;  // sfix16_En14
  wire signed [15:0] x6;  // sfix16_En14
  reg signed [15:0] x6_p;  // sfix16_En14
  wire signed [15:0] x_shift7;  // sfix16_En14
  wire signed [15:0] y_temp_0_7_1;  // sfix16_En14
  wire signed [15:0] y_temp_1_7_1;  // sfix16_En14
  wire signed [15:0] y7;  // sfix16_En14
  reg signed [15:0] y7_p;  // sfix16_En14
  wire switch_compare_1_36;
  wire signed [15:0] y_shift7;  // sfix16_En14
  wire signed [15:0] x_temp_0_7_1;  // sfix16_En14
  wire signed [15:0] x_temp_1_7_1;  // sfix16_En14
  wire signed [15:0] x7;  // sfix16_En14
  reg signed [15:0] x7_p;  // sfix16_En14
  wire signed [15:0] x_shift8;  // sfix16_En14
  wire signed [15:0] y_temp_0_8_1;  // sfix16_En14
  wire signed [15:0] y_temp_1_8_1;  // sfix16_En14
  wire signed [15:0] y8;  // sfix16_En14
  reg signed [15:0] y8_p;  // sfix16_En14
  wire switch_compare_1_37;
  wire signed [15:0] y_shift8;  // sfix16_En14
  wire signed [15:0] x_temp_0_8_1;  // sfix16_En14
  wire signed [15:0] x_temp_1_8_1;  // sfix16_En14
  wire signed [15:0] x8;  // sfix16_En14
  reg signed [15:0] x8_p;  // sfix16_En14
  wire signed [15:0] x_shift9;  // sfix16_En14
  wire signed [15:0] y_temp_0_9_1;  // sfix16_En14
  wire signed [15:0] y_temp_1_9_1;  // sfix16_En14
  wire signed [15:0] y9;  // sfix16_En14
  reg signed [15:0] y9_p;  // sfix16_En14
  wire switch_compare_1_38;
  wire signed [15:0] y_shift9;  // sfix16_En14
  wire signed [15:0] x_temp_0_9_1;  // sfix16_En14
  wire signed [15:0] x_temp_1_9_1;  // sfix16_En14
  wire signed [15:0] x9;  // sfix16_En14
  reg signed [15:0] x9_p;  // sfix16_En14
  wire signed [15:0] x_shift10;  // sfix16_En14
  wire signed [15:0] y_temp_0_10_1;  // sfix16_En14
  wire signed [15:0] y_temp_1_10_1;  // sfix16_En14
  wire signed [15:0] y10;  // sfix16_En14
  reg signed [15:0] y10_p;  // sfix16_En14
  wire switch_compare_1_39;
  wire signed [15:0] y_shift10;  // sfix16_En14
  wire signed [15:0] x_temp_0_10_1;  // sfix16_En14
  wire signed [15:0] x_temp_1_10_1;  // sfix16_En14
  wire signed [15:0] x10;  // sfix16_En14
  reg signed [15:0] x10_p;  // sfix16_En14
  wire signed [15:0] x_shift11;  // sfix16_En14
  wire signed [15:0] y_temp_0_11_1;  // sfix16_En14
  wire signed [15:0] y_temp_1_11_1;  // sfix16_En14
  wire signed [15:0] y11;  // sfix16_En14
  reg signed [15:0] y11_p;  // sfix16_En14
  wire signed [16:0] y_p_negate_cast;  // sfix17_En14
  wire signed [16:0] y_p_negate_cast_1;  // sfix17_En14
  wire signed [15:0] y_p_negate_1;  // sfix16_En14
  wire signed [15:0] sin_1;  // sfix16_En14


  assign init_guard_true_1 = 1'b1;

  always @(posedge clk or posedge reset)
    begin : matching_delays_process
      if (reset == 1'b1) begin
        matching_delays_reg <= {12{1'b0}};
      end
      else begin
        if (enb) begin
          matching_delays_reg[0] <= init_guard_true_1;
          matching_delays_reg[32'sd11:32'sd1] <= matching_delays_reg[32'sd10:32'sd0];
        end
      end
    end

  assign init_guard_true_2 = matching_delays_reg[11];

  assign sininit_guard_default = 16'sb0000000000000000;

  assign piOver2_1 = 16'sb0001100100100010;

  assign Cmp_theta_PiOver2_1 = angle > piOver2_1;

  assign switch_compare_1 = Cmp_theta_PiOver2_1 > 1'b0;

  assign negatepiOver2_cast = {piOver2_1[15], piOver2_1};
  assign negatepiOver2_cast_1 =  - (negatepiOver2_cast);
  assign negatepiOver2_1 = negatepiOver2_cast_1[15:0];

  assign Cmp_theta_negatepiOver2_1 = angle < negatepiOver2_1;

  assign switch_compare_1_1 = Cmp_theta_negatepiOver2_1 > 1'b0;

  assign Constant_1 = 1'b0;

  assign onePi_1 = 16'sb0011001001000100;

  assign thetaPlusOnePi_1 = angle + onePi_1;

  assign Cmp_thetaPlusOnepi_neg_PiOver2_1 = thetaPlusOnePi_1 >= negatepiOver2_1;

  assign switch_compare_1_2 = Cmp_thetaPlusOnepi_neg_PiOver2_1 > 1'b0;

  assign Switch3_c1_1 = (switch_compare_1_2 == 1'b0 ? Constant_1 :
              Cmp_thetaPlusOnepi_neg_PiOver2_1);

  assign Switch4_c1_1 = (switch_compare_1_1 == 1'b0 ? Constant_1 :
              Switch3_c1_1);

  assign thetaMinusOnePi_1 = angle - onePi_1;

  assign Cmp_thetaMinusOnePi_PiOver2_1 = thetaMinusOnePi_1 <= piOver2_1;

  assign switch_compare_1_3 = Cmp_thetaMinusOnePi_PiOver2_1 > 1'b0;

  assign Switch_c1_1 = (switch_compare_1_3 == 1'b0 ? Constant_1 :
              Cmp_thetaMinusOnePi_PiOver2_1);

  assign negate = (switch_compare_1 == 1'b0 ? Switch4_c1_1 :
              Switch_c1_1);

  always @(posedge clk or posedge reset)
    begin : negate_reg_process
      if (reset == 1'b1) begin
        negate_reg_reg <= {12{1'b0}};
      end
      else begin
        if (enb) begin
          negate_reg_reg[0] <= negate;
          negate_reg_reg[32'sd11:32'sd1] <= negate_reg_reg[32'sd10:32'sd0];
        end
      end
    end

  assign negate_p = negate_reg_reg[11];

  assign switch_compare_1_4 = negate_p > 1'b0;

  assign switch_compare_1_5 = Cmp_theta_negatepiOver2_1 > 1'b0;

  assign twoPi_1 = 16'sb0110010010001000;

  assign switch_compare_1_6 = Cmp_thetaPlusOnepi_neg_PiOver2_1 > 1'b0;

  assign thetaPlusTwoPi_1 = angle + twoPi_1;

  assign thetaPlusTwoPi_dtc_1 = {thetaPlusTwoPi_1[13:0], 2'b00};

  assign switch_compare_1_7 = Cmp_thetaMinusOnePi_PiOver2_1 > 1'b0;

  assign thetaMinusTwoPi_1 = angle - twoPi_1;

  assign thetaMinusTwoPi_dtc_1 = {thetaMinusTwoPi_1[13:0], 2'b00};

  assign switch_compare_1_8 = Cmp_theta_PiOver2_1 > 1'b0;

  assign moveFractionLengthUp_dtc = {angle[13:0], 2'b00};

  assign thetaPlusOnePi_dtc_1 = {thetaPlusOnePi_1[13:0], 2'b00};

  assign Switch3_1 = (switch_compare_1_6 == 1'b0 ? thetaPlusTwoPi_dtc_1 :
              thetaPlusOnePi_dtc_1);

  assign Switch4_1 = (switch_compare_1_5 == 1'b0 ? moveFractionLengthUp_dtc :
              Switch3_1);

  assign thetaMinusOnePi_dtc_1 = {thetaMinusOnePi_1[13:0], 2'b00};

  assign Switch_1 = (switch_compare_1_7 == 1'b0 ? thetaMinusTwoPi_dtc_1 :
              thetaMinusOnePi_dtc_1);

  assign corrected_theta = (switch_compare_1_8 == 1'b0 ? Switch4_1 :
              Switch_1);

  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : z0_reg_process
      if (reset == 1'b1) begin
        z0_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          z0_p <= corrected_theta;
        end
      end
    end

  assign comp_zero1 = z0_p < 16'sb0000000000000000;

  assign switch_compare_1_9 = comp_zero1 > 1'b0;

  assign lut_value_s1 = 16'sb0011001001000100;

  assign lut_value_temp_0_1_1 = z0_p - lut_value_s1;

  assign lut_value_temp_1_1_1 = z0_p + lut_value_s1;

  assign z1 = (switch_compare_1_9 == 1'b0 ? lut_value_temp_0_1_1 :
              lut_value_temp_1_1_1);

  always @(posedge clk or posedge reset)
    begin : z_reg_process
      if (reset == 1'b1) begin
        z1_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          z1_p <= z1;
        end
      end
    end

  assign comp_zero2 = z1_p < 16'sb0000000000000000;

  assign switch_compare_1_10 = comp_zero2 > 1'b0;

  assign lut_value_s2 = 16'sb0001110110101100;

  assign lut_value_temp_0_2_1 = z1_p - lut_value_s2;

  assign lut_value_temp_1_2_1 = z1_p + lut_value_s2;

  assign z2 = (switch_compare_1_10 == 1'b0 ? lut_value_temp_0_2_1 :
              lut_value_temp_1_2_1);

  always @(posedge clk or posedge reset)
    begin : z_reg_1_process
      if (reset == 1'b1) begin
        z2_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          z2_p <= z2;
        end
      end
    end

  assign comp_zero3 = z2_p < 16'sb0000000000000000;

  assign switch_compare_1_11 = comp_zero3 > 1'b0;

  assign lut_value_s3 = 16'sb0000111110101110;

  assign lut_value_temp_0_3_1 = z2_p - lut_value_s3;

  assign lut_value_temp_1_3_1 = z2_p + lut_value_s3;

  assign z3 = (switch_compare_1_11 == 1'b0 ? lut_value_temp_0_3_1 :
              lut_value_temp_1_3_1);

  always @(posedge clk or posedge reset)
    begin : z_reg_2_process
      if (reset == 1'b1) begin
        z3_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          z3_p <= z3;
        end
      end
    end

  assign comp_zero4 = z3_p < 16'sb0000000000000000;

  assign switch_compare_1_12 = comp_zero4 > 1'b0;

  assign lut_value_s4 = 16'sb0000011111110101;

  assign lut_value_temp_0_4_1 = z3_p - lut_value_s4;

  assign lut_value_temp_1_4_1 = z3_p + lut_value_s4;

  assign z4 = (switch_compare_1_12 == 1'b0 ? lut_value_temp_0_4_1 :
              lut_value_temp_1_4_1);

  always @(posedge clk or posedge reset)
    begin : z_reg_3_process
      if (reset == 1'b1) begin
        z4_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          z4_p <= z4;
        end
      end
    end

  assign comp_zero5 = z4_p < 16'sb0000000000000000;

  assign switch_compare_1_13 = comp_zero5 > 1'b0;

  assign lut_value_s5 = 16'sb0000001111111111;

  assign lut_value_temp_0_5_1 = z4_p - lut_value_s5;

  assign lut_value_temp_1_5_1 = z4_p + lut_value_s5;

  assign z5 = (switch_compare_1_13 == 1'b0 ? lut_value_temp_0_5_1 :
              lut_value_temp_1_5_1);

  always @(posedge clk or posedge reset)
    begin : z_reg_4_process
      if (reset == 1'b1) begin
        z5_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          z5_p <= z5;
        end
      end
    end

  assign comp_zero6 = z5_p < 16'sb0000000000000000;

  assign switch_compare_1_14 = comp_zero6 > 1'b0;

  assign lut_value_s6 = 16'sb0000001000000000;

  assign lut_value_temp_0_6_1 = z5_p - lut_value_s6;

  assign lut_value_temp_1_6_1 = z5_p + lut_value_s6;

  assign z6 = (switch_compare_1_14 == 1'b0 ? lut_value_temp_0_6_1 :
              lut_value_temp_1_6_1);

  always @(posedge clk or posedge reset)
    begin : z_reg_5_process
      if (reset == 1'b1) begin
        z6_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          z6_p <= z6;
        end
      end
    end

  assign comp_zero7 = z6_p < 16'sb0000000000000000;

  assign switch_compare_1_15 = comp_zero7 > 1'b0;

  assign lut_value_s7 = 16'sb0000000100000000;

  assign lut_value_temp_0_7_1 = z6_p - lut_value_s7;

  assign lut_value_temp_1_7_1 = z6_p + lut_value_s7;

  assign z7 = (switch_compare_1_15 == 1'b0 ? lut_value_temp_0_7_1 :
              lut_value_temp_1_7_1);

  always @(posedge clk or posedge reset)
    begin : z_reg_6_process
      if (reset == 1'b1) begin
        z7_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          z7_p <= z7;
        end
      end
    end

  assign comp_zero8 = z7_p < 16'sb0000000000000000;

  assign switch_compare_1_16 = comp_zero8 > 1'b0;

  assign lut_value_s8 = 16'sb0000000010000000;

  assign lut_value_temp_0_8_1 = z7_p - lut_value_s8;

  assign lut_value_temp_1_8_1 = z7_p + lut_value_s8;

  assign z8 = (switch_compare_1_16 == 1'b0 ? lut_value_temp_0_8_1 :
              lut_value_temp_1_8_1);

  always @(posedge clk or posedge reset)
    begin : z_reg_7_process
      if (reset == 1'b1) begin
        z8_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          z8_p <= z8;
        end
      end
    end

  assign comp_zero9 = z8_p < 16'sb0000000000000000;

  assign switch_compare_1_17 = comp_zero9 > 1'b0;

  assign lut_value_s9 = 16'sb0000000001000000;

  assign lut_value_temp_0_9_1 = z8_p - lut_value_s9;

  assign lut_value_temp_1_9_1 = z8_p + lut_value_s9;

  assign z9 = (switch_compare_1_17 == 1'b0 ? lut_value_temp_0_9_1 :
              lut_value_temp_1_9_1);

  always @(posedge clk or posedge reset)
    begin : z_reg_8_process
      if (reset == 1'b1) begin
        z9_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          z9_p <= z9;
        end
      end
    end

  assign comp_zero10 = z9_p < 16'sb0000000000000000;

  assign switch_compare_1_18 = comp_zero10 > 1'b0;

  assign lut_value_s10 = 16'sb0000000000100000;

  assign lut_value_temp_0_10_1 = z9_p - lut_value_s10;

  assign lut_value_temp_1_10_1 = z9_p + lut_value_s10;

  assign z10 = (switch_compare_1_18 == 1'b0 ? lut_value_temp_0_10_1 :
              lut_value_temp_1_10_1);

  always @(posedge clk or posedge reset)
    begin : z_reg_9_process
      if (reset == 1'b1) begin
        z10_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          z10_p <= z10;
        end
      end
    end

  assign comp_zero11 = z10_p < 16'sb0000000000000000;

  assign switch_compare_1_19 = comp_zero11 > 1'b0;

  assign switch_compare_1_20 = comp_zero10 > 1'b0;

  assign switch_compare_1_21 = comp_zero9 > 1'b0;

  assign switch_compare_1_22 = comp_zero8 > 1'b0;

  assign switch_compare_1_23 = comp_zero7 > 1'b0;

  assign switch_compare_1_24 = comp_zero6 > 1'b0;

  assign switch_compare_1_25 = comp_zero5 > 1'b0;

  assign switch_compare_1_26 = comp_zero4 > 1'b0;

  assign switch_compare_1_27 = comp_zero3 > 1'b0;

  assign switch_compare_1_28 = comp_zero2 > 1'b0;

  assign switch_compare_1_29 = comp_zero1 > 1'b0;

  assign y0 = 16'sb0000000000000000;

  assign x0 = 16'sb0010011011011101;

  assign y_temp_0_1_1 = y0 + x0;

  always @(posedge clk or posedge reset)
    begin : y_temp0_reg_process
      if (reset == 1'b1) begin
        y_temp_0_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          y_temp_0_p <= y_temp_0_1_1;
        end
      end
    end

  assign y_temp_1_1_1 = y0 - x0;

  always @(posedge clk or posedge reset)
    begin : y_temp_reg_process
      if (reset == 1'b1) begin
        y_temp_1_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          y_temp_1_p <= y_temp_1_1_1;
        end
      end
    end

  assign y1 = (switch_compare_1_29 == 1'b0 ? y_temp_0_p :
              y_temp_1_p);

  always @(posedge clk or posedge reset)
    begin : y_reg_process
      if (reset == 1'b1) begin
        y1_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          y1_p <= y1;
        end
      end
    end

  assign switch_compare_1_30 = comp_zero1 > 1'b0;

  assign x_temp_0_1_1 = x0 - y0;

  always @(posedge clk or posedge reset)
    begin : x_temp0_reg_process
      if (reset == 1'b1) begin
        x_temp_0_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          x_temp_0_p <= x_temp_0_1_1;
        end
      end
    end

  assign x_temp_1_1_1 = x0 + y0;

  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_temp_reg_process
      if (reset == 1'b1) begin
        x_temp_1_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          x_temp_1_p <= x_temp_1_1_1;
        end
      end
    end

  assign x1 = (switch_compare_1_30 == 1'b0 ? x_temp_0_p :
              x_temp_1_p);

  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_process
      if (reset == 1'b1) begin
        x1_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          x1_p <= x1;
        end
      end
    end

  assign x_shift2 = x1_p >>> 8'd1;

  assign y_temp_0_2_1 = y1_p + x_shift2;

  assign y_temp_1_2_1 = y1_p - x_shift2;

  assign y2 = (switch_compare_1_28 == 1'b0 ? y_temp_0_2_1 :
              y_temp_1_2_1);

  always @(posedge clk or posedge reset)
    begin : y_reg_1_process
      if (reset == 1'b1) begin
        y2_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          y2_p <= y2;
        end
      end
    end

  assign switch_compare_1_31 = comp_zero2 > 1'b0;

  assign y_shift2 = y1_p >>> 8'd1;

  assign x_temp_0_2_1 = x1_p - y_shift2;

  assign x_temp_1_2_1 = x1_p + y_shift2;

  assign x2 = (switch_compare_1_31 == 1'b0 ? x_temp_0_2_1 :
              x_temp_1_2_1);

  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_1_process
      if (reset == 1'b1) begin
        x2_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          x2_p <= x2;
        end
      end
    end

  assign x_shift3 = x2_p >>> 8'd2;

  assign y_temp_0_3_1 = y2_p + x_shift3;

  assign y_temp_1_3_1 = y2_p - x_shift3;

  assign y3 = (switch_compare_1_27 == 1'b0 ? y_temp_0_3_1 :
              y_temp_1_3_1);

  always @(posedge clk or posedge reset)
    begin : y_reg_2_process
      if (reset == 1'b1) begin
        y3_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          y3_p <= y3;
        end
      end
    end

  assign switch_compare_1_32 = comp_zero3 > 1'b0;

  assign y_shift3 = y2_p >>> 8'd2;

  assign x_temp_0_3_1 = x2_p - y_shift3;

  assign x_temp_1_3_1 = x2_p + y_shift3;

  assign x3 = (switch_compare_1_32 == 1'b0 ? x_temp_0_3_1 :
              x_temp_1_3_1);

  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_2_process
      if (reset == 1'b1) begin
        x3_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          x3_p <= x3;
        end
      end
    end

  assign x_shift4 = x3_p >>> 8'd3;

  assign y_temp_0_4_1 = y3_p + x_shift4;

  assign y_temp_1_4_1 = y3_p - x_shift4;

  assign y4 = (switch_compare_1_26 == 1'b0 ? y_temp_0_4_1 :
              y_temp_1_4_1);

  always @(posedge clk or posedge reset)
    begin : y_reg_3_process
      if (reset == 1'b1) begin
        y4_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          y4_p <= y4;
        end
      end
    end

  assign switch_compare_1_33 = comp_zero4 > 1'b0;

  assign y_shift4 = y3_p >>> 8'd3;

  assign x_temp_0_4_1 = x3_p - y_shift4;

  assign x_temp_1_4_1 = x3_p + y_shift4;

  assign x4 = (switch_compare_1_33 == 1'b0 ? x_temp_0_4_1 :
              x_temp_1_4_1);

  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_3_process
      if (reset == 1'b1) begin
        x4_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          x4_p <= x4;
        end
      end
    end

  assign x_shift5 = x4_p >>> 8'd4;

  assign y_temp_0_5_1 = y4_p + x_shift5;

  assign y_temp_1_5_1 = y4_p - x_shift5;

  assign y5 = (switch_compare_1_25 == 1'b0 ? y_temp_0_5_1 :
              y_temp_1_5_1);

  always @(posedge clk or posedge reset)
    begin : y_reg_4_process
      if (reset == 1'b1) begin
        y5_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          y5_p <= y5;
        end
      end
    end

  assign switch_compare_1_34 = comp_zero5 > 1'b0;

  assign y_shift5 = y4_p >>> 8'd4;

  assign x_temp_0_5_1 = x4_p - y_shift5;

  assign x_temp_1_5_1 = x4_p + y_shift5;

  assign x5 = (switch_compare_1_34 == 1'b0 ? x_temp_0_5_1 :
              x_temp_1_5_1);

  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_4_process
      if (reset == 1'b1) begin
        x5_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          x5_p <= x5;
        end
      end
    end

  assign x_shift6 = x5_p >>> 8'd5;

  assign y_temp_0_6_1 = y5_p + x_shift6;

  assign y_temp_1_6_1 = y5_p - x_shift6;

  assign y6 = (switch_compare_1_24 == 1'b0 ? y_temp_0_6_1 :
              y_temp_1_6_1);

  always @(posedge clk or posedge reset)
    begin : y_reg_5_process
      if (reset == 1'b1) begin
        y6_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          y6_p <= y6;
        end
      end
    end

  assign switch_compare_1_35 = comp_zero6 > 1'b0;

  assign y_shift6 = y5_p >>> 8'd5;

  assign x_temp_0_6_1 = x5_p - y_shift6;

  assign x_temp_1_6_1 = x5_p + y_shift6;

  assign x6 = (switch_compare_1_35 == 1'b0 ? x_temp_0_6_1 :
              x_temp_1_6_1);

  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_5_process
      if (reset == 1'b1) begin
        x6_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          x6_p <= x6;
        end
      end
    end

  assign x_shift7 = x6_p >>> 8'd6;

  assign y_temp_0_7_1 = y6_p + x_shift7;

  assign y_temp_1_7_1 = y6_p - x_shift7;

  assign y7 = (switch_compare_1_23 == 1'b0 ? y_temp_0_7_1 :
              y_temp_1_7_1);

  always @(posedge clk or posedge reset)
    begin : y_reg_6_process
      if (reset == 1'b1) begin
        y7_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          y7_p <= y7;
        end
      end
    end

  assign switch_compare_1_36 = comp_zero7 > 1'b0;

  assign y_shift7 = y6_p >>> 8'd6;

  assign x_temp_0_7_1 = x6_p - y_shift7;

  assign x_temp_1_7_1 = x6_p + y_shift7;

  assign x7 = (switch_compare_1_36 == 1'b0 ? x_temp_0_7_1 :
              x_temp_1_7_1);

  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_6_process
      if (reset == 1'b1) begin
        x7_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          x7_p <= x7;
        end
      end
    end

  assign x_shift8 = x7_p >>> 8'd7;

  assign y_temp_0_8_1 = y7_p + x_shift8;

  assign y_temp_1_8_1 = y7_p - x_shift8;

  assign y8 = (switch_compare_1_22 == 1'b0 ? y_temp_0_8_1 :
              y_temp_1_8_1);

  always @(posedge clk or posedge reset)
    begin : y_reg_7_process
      if (reset == 1'b1) begin
        y8_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          y8_p <= y8;
        end
      end
    end

  assign switch_compare_1_37 = comp_zero8 > 1'b0;

  assign y_shift8 = y7_p >>> 8'd7;

  assign x_temp_0_8_1 = x7_p - y_shift8;

  assign x_temp_1_8_1 = x7_p + y_shift8;

  assign x8 = (switch_compare_1_37 == 1'b0 ? x_temp_0_8_1 :
              x_temp_1_8_1);

  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_7_process
      if (reset == 1'b1) begin
        x8_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          x8_p <= x8;
        end
      end
    end

  assign x_shift9 = x8_p >>> 8'd8;

  assign y_temp_0_9_1 = y8_p + x_shift9;

  assign y_temp_1_9_1 = y8_p - x_shift9;

  assign y9 = (switch_compare_1_21 == 1'b0 ? y_temp_0_9_1 :
              y_temp_1_9_1);

  always @(posedge clk or posedge reset)
    begin : y_reg_8_process
      if (reset == 1'b1) begin
        y9_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          y9_p <= y9;
        end
      end
    end

  assign switch_compare_1_38 = comp_zero9 > 1'b0;

  assign y_shift9 = y8_p >>> 8'd8;

  assign x_temp_0_9_1 = x8_p - y_shift9;

  assign x_temp_1_9_1 = x8_p + y_shift9;

  assign x9 = (switch_compare_1_38 == 1'b0 ? x_temp_0_9_1 :
              x_temp_1_9_1);

  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_8_process
      if (reset == 1'b1) begin
        x9_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          x9_p <= x9;
        end
      end
    end

  assign x_shift10 = x9_p >>> 8'd9;

  assign y_temp_0_10_1 = y9_p + x_shift10;

  assign y_temp_1_10_1 = y9_p - x_shift10;

  assign y10 = (switch_compare_1_20 == 1'b0 ? y_temp_0_10_1 :
              y_temp_1_10_1);

  always @(posedge clk or posedge reset)
    begin : y_reg_9_process
      if (reset == 1'b1) begin
        y10_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          y10_p <= y10;
        end
      end
    end

  assign switch_compare_1_39 = comp_zero10 > 1'b0;

  assign y_shift10 = y9_p >>> 8'd9;

  assign x_temp_0_10_1 = x9_p - y_shift10;

  assign x_temp_1_10_1 = x9_p + y_shift10;

  assign x10 = (switch_compare_1_39 == 1'b0 ? x_temp_0_10_1 :
              x_temp_1_10_1);

  // Pipeline registers
  always @(posedge clk or posedge reset)
    begin : x_reg_9_process
      if (reset == 1'b1) begin
        x10_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          x10_p <= x10;
        end
      end
    end

  assign x_shift11 = x10_p >>> 8'd10;

  assign y_temp_0_11_1 = y10_p + x_shift11;

  assign y_temp_1_11_1 = y10_p - x_shift11;

  assign y11 = (switch_compare_1_19 == 1'b0 ? y_temp_0_11_1 :
              y_temp_1_11_1);

  always @(posedge clk or posedge reset)
    begin : y_reg_10_process
      if (reset == 1'b1) begin
        y11_p <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          y11_p <= y11;
        end
      end
    end

  assign y_p_negate_cast = {y11_p[15], y11_p};
  assign y_p_negate_cast_1 =  - (y_p_negate_cast);
  assign y_p_negate_1 = y_p_negate_cast_1[15:0];

  assign sin_1 = (switch_compare_1_4 == 1'b0 ? y11_p :
              y_p_negate_1);

  assign sin = (init_guard_true_2 == 1'b0 ? sininit_guard_default :
              sin_1);

endmodule  // Subsystem_ip_src_Trigonometric_Function

