// -------------------------------------------------------------
// 
// File Name: check/hdlsrc/gm_untitled1/Subsystem_ip_src_Trigonometric_Function_block.v
// Created: 2026-03-08 12:02:34
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip_src_Trigonometric_Function_block
// Source Path: gm_untitled1/Subsystem/Trigonometric Function
// Hierarchy Level: 1
// Model version: 1.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip_src_Trigonometric_Function_block
          (clk,
           reset,
           enb,
           In1,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] In1;  // sfix16_En12
  output  signed [15:0] Out1;  // sfix16_En14


  wire signed [15:0] Trigonometric_Function_pd1_out1;  // sfix16_En14


  Subsystem_ip_src_Trigonometric_Function u_Trigonometric_Function (.clk(clk),
                                                                    .reset(reset),
                                                                    .enb(enb),
                                                                    .angle(In1),  // sfix16_En12
                                                                    .sin(Trigonometric_Function_pd1_out1)  // sfix16_En14
                                                                    );

  assign Out1 = Trigonometric_Function_pd1_out1;

endmodule  // Subsystem_ip_src_Trigonometric_Function_block

