// -------------------------------------------------------------
// 
// File Name: check/hdlsrc/gm_untitled1/Subsystem_ip.v
// Created: 2026-03-08 12:02:41
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: -1
// Target subsystem base rate: -1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip
// Source Path: Subsystem_ip
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip
          (IPCORE_CLK,
           IPCORE_RESETN,
           AXI4_Lite_ACLK,
           AXI4_Lite_ARESETN,
           AXI4_Lite_AWADDR,
           AXI4_Lite_AWVALID,
           AXI4_Lite_WDATA,
           AXI4_Lite_WSTRB,
           AXI4_Lite_WVALID,
           AXI4_Lite_BREADY,
           AXI4_Lite_ARADDR,
           AXI4_Lite_ARVALID,
           AXI4_Lite_RREADY,
           AXI4_Lite_AWREADY,
           AXI4_Lite_WREADY,
           AXI4_Lite_BRESP,
           AXI4_Lite_BVALID,
           AXI4_Lite_ARREADY,
           AXI4_Lite_RDATA,
           AXI4_Lite_RRESP,
           AXI4_Lite_RVALID);


  input   IPCORE_CLK;  // ufix1
  input   IPCORE_RESETN;  // ufix1
  input   AXI4_Lite_ACLK;  // ufix1
  input   AXI4_Lite_ARESETN;  // ufix1
  input   [15:0] AXI4_Lite_AWADDR;  // ufix16
  input   AXI4_Lite_AWVALID;  // ufix1
  input   [31:0] AXI4_Lite_WDATA;  // ufix32
  input   [3:0] AXI4_Lite_WSTRB;  // ufix4
  input   AXI4_Lite_WVALID;  // ufix1
  input   AXI4_Lite_BREADY;  // ufix1
  input   [15:0] AXI4_Lite_ARADDR;  // ufix16
  input   AXI4_Lite_ARVALID;  // ufix1
  input   AXI4_Lite_RREADY;  // ufix1
  output  AXI4_Lite_AWREADY;  // ufix1
  output  AXI4_Lite_WREADY;  // ufix1
  output  [1:0] AXI4_Lite_BRESP;  // ufix2
  output  AXI4_Lite_BVALID;  // ufix1
  output  AXI4_Lite_ARREADY;  // ufix1
  output  [31:0] AXI4_Lite_RDATA;  // ufix32
  output  [1:0] AXI4_Lite_RRESP;  // ufix2
  output  AXI4_Lite_RVALID;  // ufix1


  wire reset;
  wire [31:0] ip_timestamp;  // ufix32
  wire reset_cm;  // ufix1
  wire reset_internal;  // ufix1
  wire reset_before_sync;  // ufix1
  wire write_axi_enable;  // ufix1
  wire signed [15:0] write_In1_0;  // sfix16_En12
  wire signed [15:0] write_In1_1;  // sfix16_En12
  wire signed [15:0] write_In2_0;  // sfix16_En12
  wire signed [15:0] write_In2_1;  // sfix16_En12
  wire signed [15:0] write_In3_0;  // sfix16_En12
  wire signed [15:0] write_In3_1;  // sfix16_En12
  wire signed [15:0] write_In4_0;  // sfix16_En12
  wire signed [15:0] write_In4_1;  // sfix16_En12
  wire signed [15:0] write_theta;  // sfix16_En12
  wire ce_out_sig;  // ufix1
  wire signed [15:0] y_re_sig;  // sfix16_En12
  wire signed [15:0] y_im_sig;  // sfix16_En12


  assign ip_timestamp = 32'b10011011001001111101110111110010;

  assign reset_cm =  ~ IPCORE_RESETN;

  assign reset_before_sync = reset_cm | reset_internal;

  Subsystem_ip_reset_sync u_Subsystem_ip_reset_sync_inst (.clk(IPCORE_CLK),  // ufix1
                                                          .reset_in(reset_before_sync),  // ufix1
                                                          .reset_out(reset)
                                                          );

  Subsystem_ip_dut u_Subsystem_ip_dut_inst (.clk(IPCORE_CLK),  // ufix1
                                            .reset(reset),
                                            .dut_enable(write_axi_enable),  // ufix1
                                            .In1_re(write_In1_0),  // sfix16_En12
                                            .In1_im(write_In1_1),  // sfix16_En12
                                            .In2_re(write_In2_0),  // sfix16_En12
                                            .In2_im(write_In2_1),  // sfix16_En12
                                            .In3_re(write_In3_0),  // sfix16_En12
                                            .In3_im(write_In3_1),  // sfix16_En12
                                            .In4_re(write_In4_0),  // sfix16_En12
                                            .In4_im(write_In4_1),  // sfix16_En12
                                            .theta(write_theta),  // sfix16_En12
                                            .ce_out(ce_out_sig),  // ufix1
                                            .y_re(y_re_sig),  // sfix16_En12
                                            .y_im(y_im_sig)  // sfix16_En12
                                            );

  Subsystem_ip_axi_lite u_Subsystem_ip_axi_lite_inst (.reset(reset),
                                                      .AXI4_Lite_ACLK(AXI4_Lite_ACLK),  // ufix1
                                                      .AXI4_Lite_ARESETN(AXI4_Lite_ARESETN),  // ufix1
                                                      .AXI4_Lite_AWADDR(AXI4_Lite_AWADDR),  // ufix16
                                                      .AXI4_Lite_AWVALID(AXI4_Lite_AWVALID),  // ufix1
                                                      .AXI4_Lite_WDATA(AXI4_Lite_WDATA),  // ufix32
                                                      .AXI4_Lite_WSTRB(AXI4_Lite_WSTRB),  // ufix4
                                                      .AXI4_Lite_WVALID(AXI4_Lite_WVALID),  // ufix1
                                                      .AXI4_Lite_BREADY(AXI4_Lite_BREADY),  // ufix1
                                                      .AXI4_Lite_ARADDR(AXI4_Lite_ARADDR),  // ufix16
                                                      .AXI4_Lite_ARVALID(AXI4_Lite_ARVALID),  // ufix1
                                                      .AXI4_Lite_RREADY(AXI4_Lite_RREADY),  // ufix1
                                                      .read_ip_timestamp(ip_timestamp),  // ufix32
                                                      .read_y_0(y_re_sig),  // sfix16_En12
                                                      .read_y_1(y_im_sig),  // sfix16_En12
                                                      .AXI4_Lite_AWREADY(AXI4_Lite_AWREADY),  // ufix1
                                                      .AXI4_Lite_WREADY(AXI4_Lite_WREADY),  // ufix1
                                                      .AXI4_Lite_BRESP(AXI4_Lite_BRESP),  // ufix2
                                                      .AXI4_Lite_BVALID(AXI4_Lite_BVALID),  // ufix1
                                                      .AXI4_Lite_ARREADY(AXI4_Lite_ARREADY),  // ufix1
                                                      .AXI4_Lite_RDATA(AXI4_Lite_RDATA),  // ufix32
                                                      .AXI4_Lite_RRESP(AXI4_Lite_RRESP),  // ufix2
                                                      .AXI4_Lite_RVALID(AXI4_Lite_RVALID),  // ufix1
                                                      .write_axi_enable(write_axi_enable),  // ufix1
                                                      .write_In1_0(write_In1_0),  // sfix16_En12
                                                      .write_In1_1(write_In1_1),  // sfix16_En12
                                                      .write_theta(write_theta),  // sfix16_En12
                                                      .write_In2_0(write_In2_0),  // sfix16_En12
                                                      .write_In2_1(write_In2_1),  // sfix16_En12
                                                      .write_In3_0(write_In3_0),  // sfix16_En12
                                                      .write_In3_1(write_In3_1),  // sfix16_En12
                                                      .write_In4_0(write_In4_0),  // sfix16_En12
                                                      .write_In4_1(write_In4_1),  // sfix16_En12
                                                      .reset_internal(reset_internal)  // ufix1
                                                      );

endmodule  // Subsystem_ip

