// -------------------------------------------------------------
// 
// File Name: check/hdlsrc/gm_untitled1/Subsystem_ip_dut.v
// Created: 2026-03-08 12:02:41
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_ip_dut
// Source Path: Subsystem_ip/Subsystem_ip_dut
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_ip_dut
          (clk,
           reset,
           dut_enable,
           In1_re,
           In1_im,
           In2_re,
           In2_im,
           In3_re,
           In3_im,
           In4_re,
           In4_im,
           theta,
           ce_out,
           y_re,
           y_im);


  input   clk;
  input   reset;
  input   dut_enable;  // ufix1
  input   signed [15:0] In1_re;  // sfix16_En12
  input   signed [15:0] In1_im;  // sfix16_En12
  input   signed [15:0] In2_re;  // sfix16_En12
  input   signed [15:0] In2_im;  // sfix16_En12
  input   signed [15:0] In3_re;  // sfix16_En12
  input   signed [15:0] In3_im;  // sfix16_En12
  input   signed [15:0] In4_re;  // sfix16_En12
  input   signed [15:0] In4_im;  // sfix16_En12
  input   signed [15:0] theta;  // sfix16_En12
  output  ce_out;  // ufix1
  output  signed [15:0] y_re;  // sfix16_En12
  output  signed [15:0] y_im;  // sfix16_En12


  wire enb;
  wire ce_out_sig;  // ufix1
  wire signed [15:0] y_re_sig;  // sfix16_En12
  wire signed [15:0] y_im_sig;  // sfix16_En12


  assign enb = dut_enable;

  Subsystem_ip_src_Subsystem u_Subsystem_ip_src_Subsystem (.clk(clk),
                                                           .clk_enable(enb),
                                                           .reset(reset),
                                                           .In1_re(In1_re),  // sfix16_En12
                                                           .In1_im(In1_im),  // sfix16_En12
                                                           .In2_re(In2_re),  // sfix16_En12
                                                           .In2_im(In2_im),  // sfix16_En12
                                                           .In3_re(In3_re),  // sfix16_En12
                                                           .In3_im(In3_im),  // sfix16_En12
                                                           .In4_re(In4_re),  // sfix16_En12
                                                           .In4_im(In4_im),  // sfix16_En12
                                                           .theta(theta),  // sfix16_En12
                                                           .ce_out(ce_out_sig),  // ufix1
                                                           .y_re(y_re_sig),  // sfix16_En12
                                                           .y_im(y_im_sig)  // sfix16_En12
                                                           );

  assign ce_out = ce_out_sig;

  assign y_re = y_re_sig;

  assign y_im = y_im_sig;

endmodule  // Subsystem_ip_dut

